coverage:
  range: 80..100
  round: down
  precision: 2

  status:
    project:
      default:
        target: 95%
        if_not_found: success
        if_ci_failed: error
      lib:
        target: 100%
        flags:
          - lib
      cmd:
        target: 90%
        flags:
          - cmd

ignore:
  - "cmd/repository" # ignore until we updated unit tests for it
  - "cmd/logger"     # ignore until we updated unit tests for it